name: K6 Load Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v4

      - name: Instalar dependencias Node
        run: npm install

      - name: Iniciar servidor en background
        run: npm start &

      - name: Esperar que el servidor arranque
        run: sleep 5

      - name: Instalar K6
        run: |
          sudo gpg --no-default-keyring \
            --keyring /usr/share/keyrings/k6-archive-keyring.gpg \
            --keyserver hkp://keyserver.ubuntu.com:80 \
            --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] \
            https://dl.k6.io/deb stable main" \
            | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update && sudo apt-get install k6 -y

      - name: Ejecutar pruebas K6 y enviar a Grafana Cloud
        run: k6 run load-test.js
        env:
          K6_CLOUD_TOKEN: ${{ secrets.GRAFANA_TOKEN }}
          K6_OUT: cloud

      - name: Subir resultados como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: results.json
